sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist
  user: __token__ 
  password:
    secure: "a/waYjABu3Q/7WrXbJkVZiHcvJMerBTXQun73RxCQFiDcPe+zLQ1ZVY+VdvjWD7jDFYhp/DWBd4hvfe6/UJVRu4BMfZFap1DhHYCnaQxNeguClGTN4V/+o+bwvWIc4lRkqOmPW/cgXHEeAL6aEk7xtuQpnh54JgAnw3FRLa9HCAt0VKqcgi8z9+Rhmfa4CxxJyTYsY7OSTMVnniTAvbqoTCSvBq5nTYveg81lp4kHwUzfZBxgXKMRPuC0d5Yg2N8APXwFgYCLtF5vhR6pqaDeDp+KUvNVFaGYkNaRkaxJ8geBMC6OlyOk4Vt4aonVH362xDSS+R5cRA4EsovwJpoo4eO/QFCSaBtyiRahN2kdJ3Lb9KuM9ERmV/WeHX7cHbQH0UjaCGPlu7CKoRe5UAb2Kcq6HadFwNQd3IsSwyDNC2t6yor7fqwnvgAF22fM3I3jhPPMo6CY7P4KEEkICKOZVibh4+PudhlvI7K1gltFIQ7GTcD/a2HR2SagTOPXTjFgldyScHjY82PIjkFgHfwp1grz221n9tnKB24Vlys0WtAkpTxnrQj3JNrg45UtR0cAuBRUZmT7xDJXB25CIPY22Co/QSGYSuU/IzrmfL/EwFu/2dRw8kMqFUROhZGwk1AsR89vfSQhNRRw9APAFANyRvnQFROETP7KJY7nbU2vMk="
  on:
    tags: true
    python: 3.6
  skip_cleanup: true
- provider: pypi
  distributions: sdist
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: "NPTikzAY5Hlk+qOyICmRFxnnFFhEA6vCxSVZiB3jDZtwMi3NznlF46OtIaYR/rc5KBttj+mKMdr+yG71K1F4wfLYtDV5wEmsX8pAhroVGmIlt/2ToXEJSk9JIfVVNmAtxsEdEPC9YbtdTlk2TwsXhmWl8tXtutqO6so5G3WbKJ8s06V5pCYPyVz/+1vD3Zu1SMCRGwyxjwn7j6NaYGrqG9SBCEyu0H/j3BkLr8rnYk/epiFIXLB1V69zZgw9D42xt+OpDiXwLA88w+YFbrW4OV204gqkAdme3sscVfqofPjQ24jLATQU81okoezI1SHzsonCLVyhS3QXypBEK6r2sYVboM0iHVVArUuhnlQhkeiw0QCqGEAmpf+mPontRDJ2BgCRL5Gh0VfNdnnBnOMWPffFf9YV9cZPjS9VOi4DA1bqUAPp0dKL2HkBZcPFC8e9SIUAzNha5aRo79cpfBv7xocDTRb3GZoAtkleaBPxlQRAeWqib+Hn/+948efdlJCuNeiy0k6afffBcOez7YH4BCGW2D4hBnHSua8my+GHYeogpDHn7YSdoyTIEuHJBXSwyQaFWCg9cRfuiNC5y392omD6Q4Vq/9I+mK2S8fG02vZrvcHfjESFmAwTJ4DIE4soiYWgxsVb/EEG8+DYLQSkmSW8NKsRxi1uIxK7vexL5vA="
  on:
    branch: master
    tags: false
    python: 3.6
  skip_cleanup: true
