sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist
  user: __token__ 
  password:
    secure: "a/waYjABu3Q/7WrXbJkVZiHcvJMerBTXQun73RxCQFiDcPe+zLQ1ZVY+VdvjWD7jDFYhp/DWBd4hvfe6/UJVRu4BMfZFap1DhHYCnaQxNeguClGTN4V/+o+bwvWIc4lRkqOmPW/cgXHEeAL6aEk7xtuQpnh54JgAnw3FRLa9HCAt0VKqcgi8z9+Rhmfa4CxxJyTYsY7OSTMVnniTAvbqoTCSvBq5nTYveg81lp4kHwUzfZBxgXKMRPuC0d5Yg2N8APXwFgYCLtF5vhR6pqaDeDp+KUvNVFaGYkNaRkaxJ8geBMC6OlyOk4Vt4aonVH362xDSS+R5cRA4EsovwJpoo4eO/QFCSaBtyiRahN2kdJ3Lb9KuM9ERmV/WeHX7cHbQH0UjaCGPlu7CKoRe5UAb2Kcq6HadFwNQd3IsSwyDNC2t6yor7fqwnvgAF22fM3I3jhPPMo6CY7P4KEEkICKOZVibh4+PudhlvI7K1gltFIQ7GTcD/a2HR2SagTOPXTjFgldyScHjY82PIjkFgHfwp1grz221n9tnKB24Vlys0WtAkpTxnrQj3JNrg45UtR0cAuBRUZmT7xDJXB25CIPY22Co/QSGYSuU/IzrmfL/EwFu/2dRw8kMqFUROhZGwk1AsR89vfSQhNRRw9APAFANyRvnQFROETP7KJY7nbU2vMk="
  on:
    tags: true
    python: 3.6
  skip_cleanup: true
